name: appmintic
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.0.dev <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.4
  firebase: ^9.0.2
  firebase_core: ^1.10.5
  firebase_database: ^9.0.3
  firebase_messaging: ^11.2.3
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  google_fonts: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/img/

